In [24]:
from ase.io import read

In [25]:
from ase import Atoms, Atom

In [26]:
from ase.visualize import view

In [27]:
# define an Atoms object
H2 = Atoms([Atom('H', [5., 5., 5.]),
               Atom('H', [5.74, 5., 5.])],cell=[10,10,10],pbc=True)

In [28]:
H2

Atoms(symbols='H2', pbc=True, cell=[10.0, 10.0, 10.0])

In [29]:
import numpy as np

In [30]:
H2= Atoms(H2,positions=([5,5,5],[5.74,5,5]),cell=10*np.eye(3),pbc=True)

In [31]:
H2

Atoms(symbols='H2', pbc=True, cell=[10.0, 10.0, 10.0])

In [32]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
H2.cell

Cell([10.0, 10.0, 10.0])

In [34]:
H2.get_positions()

array([[5.  , 5.  , 5.  ],
       [5.74, 5.  , 5.  ]])

In [35]:
H2.get_cell()

Cell([10.0, 10.0, 10.0])

In [36]:
H2.get_all_distances()

array([[0.  , 0.74],
       [0.74, 0.  ]])

In [37]:
H2.get_scaled_positions()

array([[0.5  , 0.5  , 0.5  ],
       [0.574, 0.5  , 0.5  ]])

In [38]:
H2.get_center_of_mass()

array([5.37, 5.  , 5.  ])

In [39]:
H2.get_global_number_of_atoms()

2

In [40]:
len(H2)

2

In [41]:
H2.cell.reciprocal()

Cell([0.1, 0.1, 0.1])

In [42]:
from ase.calculators.emt import EMT
H2.calc = EMT()

In [43]:
from ase.optimize import BFGS
from ase import units
from ase.md.langevin import Langevin
from ase.io import Trajectory,read
from ase.filters import ExpCellFilter
from ase.md.velocitydistribution import MaxwellBoltzmannDistribution

In [46]:
MaxwellBoltzmannDistribution(H2, temperature_K=300)


In [48]:
dyn = Langevin(H2,timestep=1.0 * units.fs,temperature_K=300,friction=0.01 / units.fs)


In [52]:
traj = Trajectory('md.traj', 'a', H2) 


In [53]:
dyn.attach(traj.write, interval=10)


In [58]:
dyn.run(1000)

True